
export type LULCClass = 'Forest' | 'Water' | 'Agriculture' | 'Barren' | 'Built-up';

export type Language = 'en' | 'te' | 'hi';

export type Theme = 'light' | 'dark';

export type AnalyticsMode = 'historical' | 'forecasting' | 'policy' | 'temporal';

export type Season = 'summer' | 'monsoon' | 'winter' | 'brahmotsavam';

export type MapLayer = 's1_sar' | 's2_optical' | 'lulc_grid' | 'change_heatmap';

export interface StatMetric {
  label: string;
  value: string | number;
  change?: string;
  trend: 'up' | 'down' | 'neutral';
  color: string;
}

export interface TransitionData {
  from: LULCClass;
  to: LULCClass;
  hectares: number;
}

export interface ChartDataPoint {
  name: string;
  value: number;
  color?: string;
}

export interface ComparativeDataPoint {
  name: string;
  '2018': number;
  '2024': number;
}

export interface AnalysisReport {
  id: string;
  title: string;
  summary: string;
  severity: 'low' | 'medium' | 'high';
  date: string;
  department: Department;
  dispatched?: boolean;
  lat?: number; // Added for Map plotting
  lng?: number; // Added for Map plotting
  emailBody?: string; // Content generated by Gemini
}

export enum ViewMode {
  MONITOR = 'MONITOR',
  ANALYTICS = 'ANALYTICS',
  REPORTS = 'REPORTS',
  SETTINGS = 'SETTINGS',
  SYSTEM_KERNEL = 'SYSTEM_KERNEL'
}

export interface Coordinates {
  lat: number;
  lng: number;
}

export type Department = 'Urban Planning' | 'Forestry' | 'Water Works' | 'General Administration';

export interface DepartmentConfig {
  metrics: string[]; // Keys of metrics to show
  focusArea: string;
  themeColor: string;
  rules: string[]; // Governance rules
  futureTrends: string[];
}

export interface User {
  name: string;
  role: string;
  department: Department;
  avatar: string;
}

export interface GeoPolygon {
  id: string;
  path: [number, number][]; // Polygon coordinates
  class2018: string;
  class2024: string;
  label: string;
  confidence: number;
  area_ha?: number;
}

// New Type for Grid-Based Raster Data
export interface PixelPoint {
  lat: number;
  lng: number;
  class2018: LULCClass;
  class2024: LULCClass;
  confidence: number;
  id: string;
  variation: number; // 0-1 value for texture rendering
  jitterLat: number; // Micro-jitter for organic look
  jitterLng: number; // Micro-jitter for organic look
  radius: number; // Radius in meters for organic blob size
  riskScore: number; // 0-100 Environmental Risk Score
  transitionYear: number; // The exact year (2019-2024) this pixel changed state
}

export interface LiveWeatherData {
  temperature: number;
  precipitation: number;
  cloudCover: number;
  windSpeed: number;
  isDay: boolean;
}

export interface TrendAlert {
  id: string;
  lat: number;
  lng: number;
  message: string;
  type: 'critical' | 'warning';
}

// --- NEW TYPES FOR LAYERS 2 & 3 ---

export interface SimulationScenario {
  id: string;
  label: string;
  description: string;
  impact: {
    targetClass: LULCClass;
    percentChange: number; // e.g., -0.20 for 20% reduction
    revenueImpact: number; // in Crores INR
  };
  isActive: boolean;
}

export interface EconomicMetric {
  label: string;
  value: number;
  unit: string;
  type: 'revenue' | 'cost' | 'ecological';
  description: string;
}

export interface PolicyConfig {
    bufferRadius: number; // meters
    verticalMandate: boolean;
    landBanking: boolean;
}

export interface RiskZone {
    id: string;
    lat: number;
    lng: number;
    radius: number;
    label: string;
    riskLevel: number; // 0-100
    predictedLoss: number; // hectares
    type?: 'fire' | 'flood' | 'pilgrim'; // For Temporal Layer
}
